apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qqbid1fxq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qqbid1fxq-python 
  name: qqbid1fxq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qqbid1fxq-python 
